# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('HABRAHABR', 'HABRAHABR'), ('GEEKTIMES', 'GEEKTIMES'), ('TPROGER', 'TPROGER')], max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('header', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('date_parsed', models.DateField(auto_now_add=True)),
                ('date_published', models.CharField(blank=True, max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('likes', models.CharField(blank=True, max_length=255)),
                ('add_to_favorite', models.CharField(blank=True, max_length=255)),
                ('reviews', models.CharField(blank=True, max_length=255)),
                ('unique_hash', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
