# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161211_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_to_favorite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
