# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161211_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
