# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161211_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_to_favorite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_parsed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Parsed'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.CharField(blank=True, max_length=255, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='site',
            field=models.CharField(choices=[('HABRAHABR', 'HABRAHABR'), ('GEEKTIMES', 'GEEKTIMES'), ('TPROGER', 'TPROGER'), ('GAGADGET', 'GAGADGET'), ('AIN', 'AIN')], max_length=255),
        ),
    ]
