# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161222_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Published'),
        ),
    ]
